<a href="https://colab.research.google.com/github/Shreeshambav/DeepLearning_training/blob/main/Deeplearning_LSTM_Fake_News_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
from google.colab import files
uploaded = files.upload()

Saving Train.csv to Train.csv


In [7]:
import pandas as pd

In [8]:
file_path_merged = 'Train.csv'
df=pd.read_csv(file_path_merged)

In [6]:
df.head()

text  label
0  I grew up (b. 1965) watching and loving the Th...      0
1  When I put this movie in my DVD player, and sa...      0
2  Why do people who do not know what a particula...      0
3  Even though I have great interest in Biblical ...      0
4  Im a die hard Dads Army fan and nothing will e...      1

In [9]:
df.shape

(40000, 2)

In [10]:
df.isnull().sum()

text     0
label    0
dtype: int64

In [11]:
# Drop Nan value
df = df.dropna()

In [12]:
df.shape

(40000, 2)

In [13]:
df.head()

text  label
0  I grew up (b. 1965) watching and loving the Th...      0
1  When I put this movie in my DVD player, and sa...      0
2  Why do people who do not know what a particula...      0
3  Even though I have great interest in Biblical ...      0
4  Im a die hard Dads Army fan and nothing will e...      1

In [14]:
df['text']

0        I grew up (b. 1965) watching and loving the Th...
1        When I put this movie in my DVD player, and sa...
2        Why do people who do not know what a particula...
3        Even though I have great interest in Biblical ...
4        Im a die hard Dads Army fan and nothing will e...
                               ...                        
39995    "Western Union" is something of a forgotten cl...
39996    This movie is an incredible piece of work. It ...
39997    My wife and I watched this movie because we pl...
39998    When I first watched Flatliners, I was amazed....
39999    Why would this film be so good, but only gross...
Name: text, Length: 40000, dtype: object

In [15]:
## Get the Independent Features

X=df['text']

In [16]:
X.head()

0    I grew up (b. 1965) watching and loving the Th...
1    When I put this movie in my DVD player, and sa...
2    Why do people who do not know what a particula...
3    Even though I have great interest in Biblical ...
4    Im a die hard Dads Army fan and nothing will e...
Name: text, dtype: object

In [17]:
## Get the Dependent features
y=df['label']

In [18]:
y.head()

0    0
1    0
2    0
3    0
4    1
Name: label, dtype: int64

In [19]:
X.shape

(40000,)

In [20]:
y.shape

(40000,)

In [21]:
import tensorflow as tf

In [22]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [23]:
### Set Vocabulary size a dictinary of words
voc_size=5000

In [24]:
### One Hot represenation
messages=X.copy()

In [26]:
df['text'][1]

"When I put this movie in my DVD player, and sat down with a coke and some chips, I had some expectations. I was hoping that this movie would contain some of the strong-points of the first movie: Awsome animation, good flowing story, excellent voice cast, funny comedy and a kick-ass soundtrack. But, to my disappointment, not any of this is to be found in Atlantis: Milo's Return. Had I read some reviews first, I might not have been so let down. The following paragraph will be directed to those who have seen the first movie, and who enjoyed it primarily for the points mentioned.<br /><br />When the first scene appears, your in for a shock if you just picked Atlantis: Milo's Return from the display-case at your local videoshop (or whatever), and had the expectations I had. The music feels as a bad imitation of the first movie, and the voice cast has been replaced by a not so fitting one. (With the exception of a few characters, like the voice of Sweet). The actual drawings isnt that bad, 

In [27]:
# Assuming messages is a DataFrame or a dictionary
df.text

0        I grew up (b. 1965) watching and loving the Th...
1        When I put this movie in my DVD player, and sa...
2        Why do people who do not know what a particula...
3        Even though I have great interest in Biblical ...
4        Im a die hard Dads Army fan and nothing will e...
                               ...                        
39995    "Western Union" is something of a forgotten cl...
39996    This movie is an incredible piece of work. It ...
39997    My wife and I watched this movie because we pl...
39998    When I first watched Flatliners, I was amazed....
39999    Why would this film be so good, but only gross...
Name: text, Length: 40000, dtype: object

In [28]:
messages

0        I grew up (b. 1965) watching and loving the Th...
1        When I put this movie in my DVD player, and sa...
2        Why do people who do not know what a particula...
3        Even though I have great interest in Biblical ...
4        Im a die hard Dads Army fan and nothing will e...
                               ...                        
39995    "Western Union" is something of a forgotten cl...
39996    This movie is an incredible piece of work. It ...
39997    My wife and I watched this movie because we pl...
39998    When I first watched Flatliners, I was amazed....
39999    Why would this film be so good, but only gross...
Name: text, Length: 40000, dtype: object

In [29]:
import nltk
import re
from nltk.corpus import stopwords

In [32]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [33]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', df['text'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [3]:
# from nltk.stem.porter import PorterStemmer
# ps = PorterStemmer()
# corpus = []

# # Assuming 'text' is the correct column name for text data
# for i in range(0, len(df)):
#     review = re.sub('[^a-zA-Z]', ' ', df['text'][i])  # Use the correct column name
#     review = review.lower()
#     review = review.split()

#     review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
#     review = ' '.join(review)
#     corpus.append(review)




NameError: ignored

In [34]:
corpus[1]

'put movi dvd player sat coke chip expect hope movi would contain strong point first movi awsom anim good flow stori excel voic cast funni comedi kick ass soundtrack disappoint found atlanti milo return read review first might let follow paragraph direct seen first movi enjoy primarili point mention br br first scene appear shock pick atlanti milo return display case local videoshop whatev expect music feel bad imit first movi voic cast replac fit one except charact like voic sweet actual draw isnt bad anim particular sad sight storylin also pretti weak like three episod schoobi doo singl adventur stori got last time dont misunderstand good schoobi doo episod didnt laugh singl time although might snigger twice br br audienc seen first movi especi care similar sequel fast review movi stand alon product like schoobi doo might like movi could still enjoy movi noth els suspect might good kid movi know might better milo return three episod seri cartoon channel breakfast tv'

In [35]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[1128,
  4977,
  1938,
  4191,
  3492,
  4935,
  4331,
  1938,
  1870,
  3492,
  4331,
  924,
  4331,
  1770,
  2317,
  576,
  1235,
  1770,
  673,
  3102,
  1323,
  2143,
  3069,
  2759,
  1337,
  753,
  4947,
  1861,
  4955,
  2669,
  333,
  4191,
  3059,
  2276,
  3828,
  4986,
  2006,
  465,
  4460,
  3481,
  3146,
  2184,
  3222,
  3446,
  3492,
  2751,
  1099,
  2536,
  4955,
  1235,
  317,
  3869,
  1056,
  1870,
  2851,
  3563,
  4092,
  4172,
  3752,
  1443,
  1301,
  2877,
  3717,
  3791,
  533,
  1960,
  2972,
  4259,
  758,
  3727,
  4928,
  794,
  1363,
  3233,
  223,
  3109,
  2952,
  4599,
  4231,
  4038,
  504,
  4038,
  4837,
  1737,
  2329],
 [4881,
  4947,
  2312,
  2742,
  3645,
  692,
  922,
  500,
  1861,
  4947,
  4955,
  712,
  2558,
  2006,
  1112,
  4947,
  3497,
  1988,
  4875,
  4468,
  4740,
  3417,
  1792,
  4359,
  2224,
  2688,
  4650,
  942,
  2028,
  3828,
  3212,
  1215,
  186,
  1640,
  3940,
  4357,
  1112,
  2326,
  2158,
  3077,
  1581,
  2609,
 

In [36]:
corpus[1]

'put movi dvd player sat coke chip expect hope movi would contain strong point first movi awsom anim good flow stori excel voic cast funni comedi kick ass soundtrack disappoint found atlanti milo return read review first might let follow paragraph direct seen first movi enjoy primarili point mention br br first scene appear shock pick atlanti milo return display case local videoshop whatev expect music feel bad imit first movi voic cast replac fit one except charact like voic sweet actual draw isnt bad anim particular sad sight storylin also pretti weak like three episod schoobi doo singl adventur stori got last time dont misunderstand good schoobi doo episod didnt laugh singl time although might snigger twice br br audienc seen first movi especi care similar sequel fast review movi stand alon product like schoobi doo might like movi could still enjoy movi noth els suspect might good kid movi know might better milo return three episod seri cartoon channel breakfast tv'

In [37]:
onehot_repr[1]

[4881,
 4947,
 2312,
 2742,
 3645,
 692,
 922,
 500,
 1861,
 4947,
 4955,
 712,
 2558,
 2006,
 1112,
 4947,
 3497,
 1988,
 4875,
 4468,
 4740,
 3417,
 1792,
 4359,
 2224,
 2688,
 4650,
 942,
 2028,
 3828,
 3212,
 1215,
 186,
 1640,
 3940,
 4357,
 1112,
 2326,
 2158,
 3077,
 1581,
 2609,
 4112,
 1112,
 4947,
 4530,
 3235,
 2006,
 4265,
 2905,
 2905,
 1112,
 4103,
 259,
 2296,
 3517,
 1215,
 186,
 1640,
 469,
 1678,
 3849,
 2613,
 3465,
 500,
 4973,
 4919,
 3009,
 4927,
 1112,
 4947,
 1792,
 4359,
 2952,
 821,
 1235,
 3856,
 743,
 4422,
 1792,
 2138,
 1054,
 43,
 2970,
 3009,
 1988,
 809,
 2627,
 1707,
 103,
 4794,
 423,
 4726,
 4422,
 3215,
 2211,
 4573,
 2139,
 1100,
 4776,
 4740,
 2117,
 4689,
 2172,
 4018,
 82,
 4875,
 4573,
 2139,
 2211,
 3676,
 3381,
 1100,
 2172,
 4010,
 2326,
 1546,
 2506,
 2905,
 2905,
 1524,
 4112,
 1112,
 4947,
 2481,
 4635,
 1163,
 2682,
 3365,
 4357,
 4947,
 3161,
 2084,
 92,
 4422,
 4573,
 2139,
 2326,
 4422,
 4947,
 3146,
 1056,
 4530,
 4947,
 2213,
 2639,

In [38]:
# Embedding Representation
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[1960 2972 4259 ... 4837 1737 2329]
 [4947 2213 2639 ... 3869 1691  389]
 [4152 3059 2823 ...  322 3727  952]
 ...
 [1552 4359   56 ...  290 4408 2109]
 [2905 2905 4740 ... 4253 2905 2905]
 [4103  288 2182 ... 3940 2838 3678]]


In [39]:
embedded_docs[1]

array([4947, 2213, 2639, 4818, 2326, 4875, 3336, 4947, 3776, 2326, 2006,
        186, 1640, 3215, 2211, 3563, 1435, 3869, 1691,  389], dtype=int32)

In [40]:
embedded_docs[0]

array([1960, 2972, 4259,  758, 3727, 4928,  794, 1363, 3233,  223, 3109,
       2952, 4599, 4231, 4038,  504, 4038, 4837, 1737, 2329], dtype=int32)

In [41]:
## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [42]:
len(embedded_docs),y.shape

(40000, (40000,))

In [43]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [44]:
X_final.shape,y_final.shape

((40000, 20), (40000,))

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [46]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
419/419 [==============================] - 23s 45ms/step - loss: 0.5309 - accuracy: 0.7230 - val_loss: 0.4853 - val_accuracy: 0.7654
Epoch 2/10
419/419 [==============================] - 18s 42ms/step - loss: 0.4341 - accuracy: 0.7979 - val_loss: 0.4811 - val_accuracy: 0.7664
Epoch 3/10
419/419 [==============================] - 20s 48ms/step - loss: 0.3994 - accuracy: 0.8209 - val_loss: 0.4923 - val_accuracy: 0.7589
Epoch 4/10
419/419 [==============================] - 18s 42ms/step - loss: 0.3648 - accuracy: 0.8397 - val_loss: 0.5222 - val_accuracy: 0.7556
Epoch 5/10
419/419 [==============================] - 20s 48ms/step - loss: 0.3290 - accuracy: 0.8572 - val_loss: 0.5643 - val_accuracy: 0.7475
Epoch 6/10
419/419 [==============================] - 17s 41ms/step - loss: 0.2832 - accuracy: 0.8787 - val_loss: 0.6298 - val_accuracy: 0.7429
Epoch 7/10
419/419 [==============================] - 18s 43ms/step - loss: 0.2428 - accuracy: 0.8998 - val_loss: 0.7337 - val_accuracy:

In [47]:
# Adding drop out if required
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [48]:
# Performance Metrics And Accuracy
y_pred=model.predict(X_test)

413/413 [==============================] - 4s 7ms/step


In [49]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [50]:
from sklearn.metrics import confusion_matrix

In [51]:
confusion_matrix(y_test,y_pred)

array([[6545,    0],
       [6655,    0]])

In [52]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.49583333333333335

In [53]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.50      1.00      0.66      6545
           1       0.00      0.00      0.00      6655

    accuracy                           0.50     13200
   macro avg       0.25      0.50      0.33     13200
weighted avg       0.25      0.50      0.33     13200



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
