<a href="https://colab.research.google.com/github/Shreeshambav/DeepLearning_training/blob/main/Deeplearning_LSTM_UNIVARIATE_Multivariate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Univariate LSTM Models
# Data Preparation
# Vanilla LSTM
# Stacked LSTM
# Bidirectional LSTM
# CNN LSTM
# ConvLSTM

In [ ]:
from google.colab import files
uploaded = files.upload()

In [2]:
from numpy import array
# univariate lstm example
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

# Split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = [], []
    for i in range(len(sequence) - n_steps):
        # Define the end of the input sequence
        end_ix = i + n_steps
        # Gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

# Define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# Choose a number of time steps
n_steps = 3
# Split into samples
X, y = split_sequence(raw_seq, n_steps)

# Print the prepared data
for i in range(len(X)):
    print(f"Input: {X[i]} => Output: {y[i]}")

# Vanilla LSTM
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

# Define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# Fit model
model.fit(X, y, epochs=200, verbose=1)

# Demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

Input: [10 20 30] => Output: 40
Input: [20 30 40] => Output: 50
Input: [30 40 50] => Output: 60
Input: [40 50 60] => Output: 70
Input: [50 60 70] => Output: 80
Input: [60 70 80] => Output: 90
Epoch 1/200
1/1 [==============================] - 2s 2s/step - loss: 5380.4097
Epoch 2/200
1/1 [==============================] - 0s 10ms/step - loss: 5252.2090
Epoch 3/200
1/1 [==============================] - 0s 12ms/step - loss: 5126.6001
Epoch 4/200
1/1 [==============================] - 0s 11ms/step - loss: 5003.3906
Epoch 5/200
1/1 [==============================] - 0s 16ms/step - loss: 4882.7290
Epoch 6/200
1/1 [==============================] - 0s 11ms/step - loss: 4765.4409
Epoch 7/200
1/1 [==============================] - 0s 13ms/step - loss: 4651.3682
Epoch 8/200
1/1 [==============================] - 0s 10ms/step - loss: 4540.8652
Epoch 9/200
1/1 [==============================] - 0s 10ms/step - loss: 4433.8955
Epoch 10/200
1/1 [==============================] - 0s 10ms/step - loss:

In [3]:
####### STACKED LSTM #################
from numpy import array
# STACKED lstm example
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

# Split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = [], []
    for i in range(len(sequence) - n_steps):
        # Define the end of the input sequence
        end_ix = i + n_steps
        # Gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

# Define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# Choose a number of time steps
n_steps = 3
# Split into samples
X, y = split_sequence(raw_seq, n_steps)

# Print the prepared data
for i in range(len(X)):
    print(f"Input: {X[i]} => Output: {y[i]}")

# Stacked LSTM
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

# Define model
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# Fit model
model.fit(X, y, epochs=200, verbose=0)

# Demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

Input: [10 20 30] => Output: 40
Input: [20 30 40] => Output: 50
Input: [30 40 50] => Output: 60
Input: [40 50 60] => Output: 70
Input: [50 60 70] => Output: 80
Input: [60 70 80] => Output: 90
[[103.245705]]


In [4]:
###### Bidirectional LSTM #################
from numpy import array
# ###### Bidirectional LSTM #################

from numpy import array
from keras.models import Sequential
from keras.layers import LSTM, Dense, Bidirectional

# Split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = [], []
    for i in range(len(sequence) - n_steps):
        # Define the end of the input sequence
        end_ix = i + n_steps
        # Gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

# Define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# Choose a number of time steps
n_steps = 3
# Split into samples
X, y = split_sequence(raw_seq, n_steps)

# Print the prepared data
for i in range(len(X)):
    print(f"Input: {X[i]} => Output: {y[i]}")

# Stacked LSTM
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

# Define model
model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# Fit model
model.fit(X, y, epochs=200, verbose=0)

# Demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

Input: [10 20 30] => Output: 40
Input: [20 30 40] => Output: 50
Input: [30 40 50] => Output: 60
Input: [40 50 60] => Output: 70
Input: [50 60 70] => Output: 80
Input: [60 70 80] => Output: 90
[[101.13983]]


In [1]:
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM, Dense, Bidirectional, TimeDistributed, Conv1D, MaxPooling1D, Flatten

# Split a CNN LSTM sequence into samples
def split_sequence(sequence, n_steps):
    X, y = [], []
    for i in range(len(sequence) - n_steps):
        end_ix = i + n_steps
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

# Define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# Choose a number of time steps
n_steps = 3
# Split into samples
X, y = split_sequence(raw_seq, n_steps)

# Print the prepared data
for i in range(len(X)):
    print(f"Input: {X[i]} => Output: {y[i]}")

# CNN LSTM
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

# Define model
model = Sequential()
model.add(TimeDistributed(Conv1D(filters=64, kernel_size=1, activation='relu'), input_shape=(None, n_steps, n_features)))
model.add(TimeDistributed(MaxPooling1D(pool_size=2)))
model.add(TimeDistributed(Flatten()))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# Fit model
model.fit(X, y, epochs=200, verbose=0)

Input: [10 20 30] => Output: 40
Input: [20 30 40] => Output: 50
Input: [30 40 50] => Output: 60
Input: [40 50 60] => Output: 70
Input: [50 60 70] => Output: 80
Input: [60 70 80] => Output: 90


ValueError: ignored

In [2]:
############ CONV LSTM ############################
import numpy as np
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import ConvLSTM2D

# Split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = [], []
    for i in range(len(sequence) - n_steps):
        end_ix = i + n_steps
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

# Define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# Choose a number of time steps
n_steps = 3
# Split into samples
X, y = split_sequence(raw_seq, n_steps)

# Print the prepared data
for i in range(len(X)):
    print(f"Input: {X[i]} => Output: {y[i]}")

# Define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]

# Choose a number of time steps
n_steps = 4

# Split into samples
X, y = split_sequence(raw_seq, n_steps)

# Reshape from [samples, timesteps] into [samples, timesteps, rows, columns, features]
n_features = 1
n_seq = 2
n_steps = 2
X = X.reshape((X.shape[0], n_seq, 1, n_steps, n_features))

# Define model
model = Sequential()
model.add(ConvLSTM2D(filters=64, kernel_size=(1,2), activation='relu', input_shape=(n_seq, 1, n_steps, n_features)))
model.add(Flatten())
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# Fit model
model.fit(X, y, epochs=200, verbose=0)

# Demonstrate prediction
x_input = array([60, 70, 80, 90])
x_input = x_input.reshape((1, n_seq, 1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

Input: [10 20 30] => Output: 40
Input: [20 30 40] => Output: 50
Input: [30 40 50] => Output: 60
Input: [40 50 60] => Output: 70
Input: [50 60 70] => Output: 80
Input: [60 70 80] => Output: 90
[[105.67249]]


In [1]:
"""
Multivariate LSTM Models
Multivariate time series data means data where there is more than one observation for each time step.

There are two main models that we may require with multivariate time series data; they are:

Multiple Input Series.
Multiple Parallel Series.
"""
import numpy as np
from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

# Split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = [], []
    for i in range(len(sequence) - n_steps):
        end_ix = i + n_steps
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)


# Define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])

# Convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))

# Horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))

# Choose a number of time steps
n_steps = 3

# Convert into input/output
X, y = split_sequence(dataset, n_steps)

print(X.shape, y.shape)
# summarize the data
for i in range(len(X)):
 print(X[i], y[i])

# The dataset knows the number of features, e.g. 2
n_features = X.shape[2]

# Define model - Vanila LSTM
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# fit model
model.fit(X, y, epochs=200, verbose=1)

# # Demonstrate prediction
x_input = array([[80, 85], [90, 95], [100, 105]])
x_input = x_input.reshape((1, n_steps, n_features))  # Corrected reshaping
yhat = model.predict(x_input, verbose=0)
print(yhat)

(6, 3, 3) (6, 3)
[[10 15 25]
 [20 25 45]
 [30 35 65]] [40 45 85]
[[20 25 45]
 [30 35 65]
 [40 45 85]] [ 50  55 105]
[[ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]] [ 60  65 125]
[[ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]] [ 70  75 145]
[[ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]] [ 80  85 165]
[[ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]] [ 90  95 185]


Epoch 1/200
1/1 [==============================] - 6s 6s/step - loss: 10403.8721
Epoch 2/200
1/1 [==============================] - 0s 15ms/step - loss: 10286.2334
Epoch 3/200
1/1 [==============================] - 0s 13ms/step - loss: 10173.7959
Epoch 4/200
1/1 [==============================] - 0s 15ms/step - loss: 10064.0928
Epoch 5/200
1/1 [==============================] - 0s 15ms/step - loss: 9956.4180
Epoch 6/200
1/1 [==============================] - 0s 15ms/step - loss: 9851.5488
Epoch 7/200
1/1 [==============================] - 0s 15ms/step - loss: 9751.1289
Epoch 8/200
1/1 [==============================] - 0s 17ms/step - loss: 9657.9502
Epoch 9/200
1/1 [==============================] - 0s 19ms/step - loss: 9572.7227
Epoch 10/200
1/1 [==============================] - 0s 16ms/step - loss: 9492.3438
Epoch 11/200
1/1 [==============================] - 0s 17ms/step - loss: 9411.0742
Epoch 12/200
1/1 [==============================] - 0s 15ms/step - loss: 9324.7217
Epoch 13/20

ValueError: ignored