<a href="https://colab.research.google.com/github/Shreeshambav/DeepLearning_training/blob/main/Deeplearning_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [3]:
### Vocabulary size
voc_size=500

In [4]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[257, 201, 60, 80], [257, 201, 60, 204], [257, 421, 60, 172], [71, 368, 315, 40, 239], [71, 368, 315, 40, 224], [405, 257, 248, 60, 455], [453, 268, 124, 40]]


In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [8]:
## Pre padding done to make sure sentence size are of equal
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 257 201  60  80]
 [  0   0   0   0 257 201  60 204]
 [  0   0   0   0 257 421  60 172]
 [  0   0   0  71 368 315  40 239]
 [  0   0   0  71 368 315  40 224]
 [  0   0   0 405 257 248  60 455]
 [  0   0   0   0 453 268 124  40]]


In [9]:
# Feature represenation size or dimension is 10
dim=10

In [10]:
# To fetch first sentence from the dataset - represented in the form of index format
embedded_docs[0]

array([  0,   0,   0,   0, 257, 201,  60,  80], dtype=int32)

In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
# The prediction done for the first statement
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 121ms/step


array([[ 0.00763442,  0.04820207, -0.00385419, -0.0247496 ,  0.00447069,
        -0.0402303 , -0.02278006, -0.03295274,  0.04609067,  0.04358969],
       [ 0.00763442,  0.04820207, -0.00385419, -0.0247496 ,  0.00447069,
        -0.0402303 , -0.02278006, -0.03295274,  0.04609067,  0.04358969],
       [ 0.00763442,  0.04820207, -0.00385419, -0.0247496 ,  0.00447069,
        -0.0402303 , -0.02278006, -0.03295274,  0.04609067,  0.04358969],
       [ 0.00763442,  0.04820207, -0.00385419, -0.0247496 ,  0.00447069,
        -0.0402303 , -0.02278006, -0.03295274,  0.04609067,  0.04358969],
       [ 0.00728605,  0.03673721, -0.04414064, -0.02770789, -0.00858017,
        -0.03150075, -0.00856645,  0.03918313,  0.03515283,  0.00739992],
       [ 0.02802907,  0.04920704,  0.01104913, -0.02248011, -0.03682252,
         0.04415134,  0.04816052, -0.04663315, -0.03476059,  0.00133107],
       [ 0.02132853, -0.0067235 , -0.00251565, -0.0097675 ,  0.04785081,
        -0.04088154, -0.01146964, -0.00812043

In [14]:
# The prediction done for all the statements
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 35ms/step
[[[ 7.6344237e-03  4.8202071e-02 -3.8541928e-03 -2.4749601e-02
    4.4706948e-03 -4.0230297e-02 -2.2780061e-02 -3.2952741e-02
    4.6090674e-02  4.3589685e-02]
  [ 7.6344237e-03  4.8202071e-02 -3.8541928e-03 -2.4749601e-02
    4.4706948e-03 -4.0230297e-02 -2.2780061e-02 -3.2952741e-02
    4.6090674e-02  4.3589685e-02]
  [ 7.6344237e-03  4.8202071e-02 -3.8541928e-03 -2.4749601e-02
    4.4706948e-03 -4.0230297e-02 -2.2780061e-02 -3.2952741e-02
    4.6090674e-02  4.3589685e-02]
  [ 7.6344237e-03  4.8202071e-02 -3.8541928e-03 -2.4749601e-02
    4.4706948e-03 -4.0230297e-02 -2.2780061e-02 -3.2952741e-02
    4.6090674e-02  4.3589685e-02]
  [ 7.2860494e-03  3.6737215e-02 -4.4140637e-02 -2.7707888e-02
   -8.5801706e-03 -3.1500746e-02 -8.5664503e-03  3.9183129e-02
    3.5152826e-02  7.3999166e-03]
  [ 2.8029073e-02  4.9207043e-02  1.1049129e-02 -2.2480106e-02
   -3.6822520e-02  4.4151340e-02  4.8160519e-02 -4.6633150e-02
   -3.4760594e-02  1.3

In [15]:
### Assignment
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [16]:
### Vocabulary size
voc_size=1000

In [17]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[469, 818, 117, 228, 399, 842], [456, 539, 117, 870, 488, 576], [177, 968, 131, 528], [469, 357, 117, 422, 469, 94], [183, 181, 593, 117, 870, 488, 576], [881, 117, 870, 488, 664, 266]]


In [18]:
## pre padding
sent_length=10
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 469 818 117 228 399 842]
 [  0   0   0   0 456 539 117 870 488 576]
 [  0   0   0   0   0   0 177 968 131 528]
 [  0   0   0   0 469 357 117 422 469  94]
 [  0   0   0 183 181 593 117 870 488 576]
 [  0   0   0   0 881 117 870 488 664 266]]


In [19]:
## 10 feature dimesnions
dim=15

In [20]:
model=Sequential()
model.add(Embedding(voc_size,15,input_length=sent_length))
model.compile('adam','mse')

In [21]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 10, 15)            15000     
                                                                 
Total params: 15,000
Trainable params: 15,000
Non-trainable params: 0
_________________________________________________________________


In [22]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 41ms/step


array([[-0.02929249,  0.00754064, -0.01028887, -0.03901839, -0.011235  ,
         0.04144523, -0.02216851, -0.00449659, -0.04865871, -0.0425083 ,
         0.03237725, -0.02317288, -0.01795205,  0.00163057, -0.0035516 ],
       [-0.02929249,  0.00754064, -0.01028887, -0.03901839, -0.011235  ,
         0.04144523, -0.02216851, -0.00449659, -0.04865871, -0.0425083 ,
         0.03237725, -0.02317288, -0.01795205,  0.00163057, -0.0035516 ],
       [-0.02929249,  0.00754064, -0.01028887, -0.03901839, -0.011235  ,
         0.04144523, -0.02216851, -0.00449659, -0.04865871, -0.0425083 ,
         0.03237725, -0.02317288, -0.01795205,  0.00163057, -0.0035516 ],
       [-0.02929249,  0.00754064, -0.01028887, -0.03901839, -0.011235  ,
         0.04144523, -0.02216851, -0.00449659, -0.04865871, -0.0425083 ,
         0.03237725, -0.02317288, -0.01795205,  0.00163057, -0.0035516 ],
       [ 0.04830188, -0.03398655,  0.02538521, -0.02674166,  0.03799481,
        -0.00096227, -0.00870059, -0.04428459, 

In [23]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 45ms/step
[[[-0.02929249  0.00754064 -0.01028887 -0.03901839 -0.011235
    0.04144523 -0.02216851 -0.00449659 -0.04865871 -0.0425083
    0.03237725 -0.02317288 -0.01795205  0.00163057 -0.0035516 ]
  [-0.02929249  0.00754064 -0.01028887 -0.03901839 -0.011235
    0.04144523 -0.02216851 -0.00449659 -0.04865871 -0.0425083
    0.03237725 -0.02317288 -0.01795205  0.00163057 -0.0035516 ]
  [-0.02929249  0.00754064 -0.01028887 -0.03901839 -0.011235
    0.04144523 -0.02216851 -0.00449659 -0.04865871 -0.0425083
    0.03237725 -0.02317288 -0.01795205  0.00163057 -0.0035516 ]
  [-0.02929249  0.00754064 -0.01028887 -0.03901839 -0.011235
    0.04144523 -0.02216851 -0.00449659 -0.04865871 -0.0425083
    0.03237725 -0.02317288 -0.01795205  0.00163057 -0.0035516 ]
  [ 0.04830188 -0.03398655  0.02538521 -0.02674166  0.03799481
   -0.00096227 -0.00870059 -0.04428459 -0.03511601  0.01366213
   -0.03974396 -0.01879936  0.0492052  -0.0409025  -0.03909956]
  [ 0.0191