<a href="https://colab.research.google.com/github/Shreeshambav/DeepLearning_training/blob/main/Deeplearning_LSTM_UNIVARIATE_Multivariate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Univariate LSTM Models
# Data Preparation
# Vanilla LSTM
# Stacked LSTM
# Bidirectional LSTM
# CNN LSTM
# ConvLSTM
# These terms refer to different variations of Recurrent Neural Networks (RNNs) and their combinations with other neural network architectures. Let's break down the differences between each of them:

#     Vanilla LSTM (Long Short-Term Memory):
#         A Vanilla LSTM is a basic implementation of the LSTM architecture, which is a type of RNN.
#         It is designed to capture long-range dependencies and handle vanishing gradient problems in sequential data.
#         It has a memory cell that allows it to store and retrieve information over long sequences.

#     Stacked LSTM:
#         Stacked LSTM involves using multiple layers of LSTM units.
#         Each layer feeds its outputs as input to the next layer.
#         This architecture can capture more complex patterns and hierarchical dependencies in sequential data.

#     Bidirectional LSTM:
#         A Bidirectional LSTM processes the input sequence in both forward and backward directions.
#         This allows the network to capture past and future context, improving its ability to understand the sequence.

#     CNN-LSTM:
#         A combination of Convolutional Neural Networks (CNNs) and LSTMs.
#         CNNs are used to extract features from the input sequence, and the LSTM is used to process the extracted features.
#         Often used for spatiotemporal data, where both spatial and temporal patterns need to be captured.

#     ConvLSTM:
#         ConvLSTM is an extension of the LSTM architecture that includes convolutional operations within the LSTM units.
#         It's designed to process both spatial and temporal data simultaneously.
#         Suitable for sequences with grid-like structures (e.g., images over time), as it can capture spatial dependencies.

# In summary:

#     Vanilla LSTM is a fundamental architecture for sequential data.
#     Stacked LSTM adds depth to LSTM networks to capture more complex patterns.
#     Bidirectional LSTM improves context understanding by processing data in both directions.
#     CNN-LSTM combines CNNs and LSTMs for spatiotemporal data.
#     ConvLSTM combines LSTMs with convolutional operations for grid-like sequences.

# The choice of architecture depends on the nature of your data and the patterns you want to capture. Experimentation and understanding the characteristics of each architecture are essential for selecting the appropriate one for your specific task.

In [ ]:
from google.colab import files
uploaded = files.upload()

In [2]:
from numpy import array
# univariate lstm example
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

# Split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = [], []
    for i in range(len(sequence) - n_steps):
        # Define the end of the input sequence
        end_ix = i + n_steps
        # Gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

# Define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# Choose a number of time steps
n_steps = 3
# Split into samples
X, y = split_sequence(raw_seq, n_steps)

# Print the prepared data
for i in range(len(X)):
    print(f"Input: {X[i]} => Output: {y[i]}")

# Vanilla LSTM
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

# Define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# Fit model
model.fit(X, y, epochs=200, verbose=1)

# Demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

Input: [10 20 30] => Output: 40
Input: [20 30 40] => Output: 50
Input: [30 40 50] => Output: 60
Input: [40 50 60] => Output: 70
Input: [50 60 70] => Output: 80
Input: [60 70 80] => Output: 90
Epoch 1/200
1/1 [==============================] - 2s 2s/step - loss: 5380.4097
Epoch 2/200
1/1 [==============================] - 0s 10ms/step - loss: 5252.2090
Epoch 3/200
1/1 [==============================] - 0s 12ms/step - loss: 5126.6001
Epoch 4/200
1/1 [==============================] - 0s 11ms/step - loss: 5003.3906
Epoch 5/200
1/1 [==============================] - 0s 16ms/step - loss: 4882.7290
Epoch 6/200
1/1 [==============================] - 0s 11ms/step - loss: 4765.4409
Epoch 7/200
1/1 [==============================] - 0s 13ms/step - loss: 4651.3682
Epoch 8/200
1/1 [==============================] - 0s 10ms/step - loss: 4540.8652
Epoch 9/200
1/1 [==============================] - 0s 10ms/step - loss: 4433.8955
Epoch 10/200
1/1 [==============================] - 0s 10ms/step - loss:

In [3]:
####### STACKED LSTM #################
from numpy import array
# STACKED lstm example
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

# Split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = [], []
    for i in range(len(sequence) - n_steps):
        # Define the end of the input sequence
        end_ix = i + n_steps
        # Gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

# Define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# Choose a number of time steps
n_steps = 3
# Split into samples
X, y = split_sequence(raw_seq, n_steps)

# Print the prepared data
for i in range(len(X)):
    print(f"Input: {X[i]} => Output: {y[i]}")

# Stacked LSTM
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

# Define model
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# Fit model
model.fit(X, y, epochs=200, verbose=0)

# Demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

Input: [10 20 30] => Output: 40
Input: [20 30 40] => Output: 50
Input: [30 40 50] => Output: 60
Input: [40 50 60] => Output: 70
Input: [50 60 70] => Output: 80
Input: [60 70 80] => Output: 90
[[103.245705]]


In [4]:
###### Bidirectional LSTM #################
from numpy import array
# ###### Bidirectional LSTM #################

from numpy import array
from keras.models import Sequential
from keras.layers import LSTM, Dense, Bidirectional

# Split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = [], []
    for i in range(len(sequence) - n_steps):
        # Define the end of the input sequence
        end_ix = i + n_steps
        # Gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

# Define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# Choose a number of time steps
n_steps = 3
# Split into samples
X, y = split_sequence(raw_seq, n_steps)

# Print the prepared data
for i in range(len(X)):
    print(f"Input: {X[i]} => Output: {y[i]}")

# Stacked LSTM
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

# Define model
model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# Fit model
model.fit(X, y, epochs=200, verbose=0)

# Demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

Input: [10 20 30] => Output: 40
Input: [20 30 40] => Output: 50
Input: [30 40 50] => Output: 60
Input: [40 50 60] => Output: 70
Input: [50 60 70] => Output: 80
Input: [60 70 80] => Output: 90
[[101.13983]]


In [1]:
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM, Dense, Bidirectional, TimeDistributed, Conv1D, MaxPooling1D, Flatten

# Split a CNN LSTM sequence into samples
def split_sequence(sequence, n_steps):
    X, y = [], []
    for i in range(len(sequence) - n_steps):
        end_ix = i + n_steps
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

# Define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# Choose a number of time steps
n_steps = 3
# Split into samples
X, y = split_sequence(raw_seq, n_steps)

# Print the prepared data
for i in range(len(X)):
    print(f"Input: {X[i]} => Output: {y[i]}")

# CNN LSTM
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

# Define model
model = Sequential()
model.add(TimeDistributed(Conv1D(filters=64, kernel_size=1, activation='relu'), input_shape=(None, n_steps, n_features)))
model.add(TimeDistributed(MaxPooling1D(pool_size=2)))
model.add(TimeDistributed(Flatten()))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# Fit model
model.fit(X, y, epochs=200, verbose=0)

Input: [10 20 30] => Output: 40
Input: [20 30 40] => Output: 50
Input: [30 40 50] => Output: 60
Input: [40 50 60] => Output: 70
Input: [50 60 70] => Output: 80
Input: [60 70 80] => Output: 90


ValueError: ignored

In [2]:
############ CONV LSTM ############################
import numpy as np
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import ConvLSTM2D

# Split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = [], []
    for i in range(len(sequence) - n_steps):
        end_ix = i + n_steps
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

# Define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# Choose a number of time steps
n_steps = 3
# Split into samples
X, y = split_sequence(raw_seq, n_steps)

# Print the prepared data
for i in range(len(X)):
    print(f"Input: {X[i]} => Output: {y[i]}")

# Define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]

# Choose a number of time steps
n_steps = 4

# Split into samples
X, y = split_sequence(raw_seq, n_steps)

# Reshape from [samples, timesteps] into [samples, timesteps, rows, columns, features]
n_features = 1
n_seq = 2
n_steps = 2
X = X.reshape((X.shape[0], n_seq, 1, n_steps, n_features))

# Define model
model = Sequential()
model.add(ConvLSTM2D(filters=64, kernel_size=(1,2), activation='relu', input_shape=(n_seq, 1, n_steps, n_features)))
model.add(Flatten())
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# Fit model
model.fit(X, y, epochs=200, verbose=0)

# Demonstrate prediction
x_input = array([60, 70, 80, 90])
x_input = x_input.reshape((1, n_seq, 1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

Input: [10 20 30] => Output: 40
Input: [20 30 40] => Output: 50
Input: [30 40 50] => Output: 60
Input: [40 50 60] => Output: 70
Input: [50 60 70] => Output: 80
Input: [60 70 80] => Output: 90
[[105.67249]]


In [1]:
"""
Multivariate LSTM Models
Multivariate time series data means data where there is more than one observation for each time step.

There are two main models that we may require with multivariate time series data; they are:

Multiple Input Series.
Multiple Parallel Series.
"""
import numpy as np
from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

# Split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = [], []
    for i in range(len(sequence) - n_steps):
        end_ix = i + n_steps
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)


# Define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])

# Convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))

# Horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))

# Choose a number of time steps
n_steps = 3

# Convert into input/output
X, y = split_sequence(dataset, n_steps)

print(X.shape, y.shape)
# summarize the data
for i in range(len(X)):
 print(X[i], y[i])

# The dataset knows the number of features, e.g. 2
n_features = X.shape[2]

# Define model - Vanila LSTM
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# fit model
model.fit(X, y, epochs=200, verbose=1)

# # Demonstrate prediction
x_input = array([[80, 85], [90, 95], [100, 105]])
x_input = x_input.reshape((1, n_steps, n_features))  # Corrected reshaping
yhat = model.predict(x_input, verbose=0)
print(yhat)

(6, 3, 3) (6, 3)
[[10 15 25]
 [20 25 45]
 [30 35 65]] [40 45 85]
[[20 25 45]
 [30 35 65]
 [40 45 85]] [ 50  55 105]
[[ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]] [ 60  65 125]
[[ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]] [ 70  75 145]
[[ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]] [ 80  85 165]
[[ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]] [ 90  95 185]


Epoch 1/200
1/1 [==============================] - 6s 6s/step - loss: 10403.8721
Epoch 2/200
1/1 [==============================] - 0s 15ms/step - loss: 10286.2334
Epoch 3/200
1/1 [==============================] - 0s 13ms/step - loss: 10173.7959
Epoch 4/200
1/1 [==============================] - 0s 15ms/step - loss: 10064.0928
Epoch 5/200
1/1 [==============================] - 0s 15ms/step - loss: 9956.4180
Epoch 6/200
1/1 [==============================] - 0s 15ms/step - loss: 9851.5488
Epoch 7/200
1/1 [==============================] - 0s 15ms/step - loss: 9751.1289
Epoch 8/200
1/1 [==============================] - 0s 17ms/step - loss: 9657.9502
Epoch 9/200
1/1 [==============================] - 0s 19ms/step - loss: 9572.7227
Epoch 10/200
1/1 [==============================] - 0s 16ms/step - loss: 9492.3438
Epoch 11/200
1/1 [==============================] - 0s 17ms/step - loss: 9411.0742
Epoch 12/200
1/1 [==============================] - 0s 15ms/step - loss: 9324.7217
Epoch 13/20

ValueError: ignored

In [2]:
# Multivariate Multi parallel lstm example
import numpy as np
from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

# Split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = [], []
    for i in range(len(sequence) - n_steps):
        end_ix = i + n_steps
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

# Define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])

# Convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))

# Horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))

# Choose a number of time steps
n_steps = 3

# Convert into input/output
X, y = split_sequence(dataset, n_steps)

print(X.shape, y.shape)
# summarize the data
for i in range(len(X)):
 print(X[i], y[i])

# The dataset knows the number of features, e.g. 2
n_features = X.shape[2]

# define model - Stacked
model = Sequential()
model.add(LSTM(100, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
model.add(LSTM(100, activation='relu'))
model.add(Dense(n_features))
model.compile(optimizer='adam', loss='mse')

# fit model
model.fit(X, y, epochs=400, verbose=1)

# demonstrate prediction
x_input = array([[70,75,145], [80,85,165], [90,95,185]])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

(6, 3, 3) (6, 3)
[[10 15 25]
 [20 25 45]
 [30 35 65]] [40 45 85]
[[20 25 45]
 [30 35 65]
 [40 45 85]] [ 50  55 105]
[[ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]] [ 60  65 125]
[[ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]] [ 70  75 145]
[[ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]] [ 80  85 165]
[[ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]] [ 90  95 185]
Epoch 1/400
1/1 [==============================] - 3s 3s/step - loss: 9804.2568
Epoch 2/400
1/1 [==============================] - 0s 25ms/step - loss: 9409.4463
Epoch 3/400
1/1 [==============================] - 0s 22ms/step - loss: 9079.2490
Epoch 4/400
1/1 [==============================] - 0s 22ms/step - loss: 8816.3281
Epoch 5/400
1/1 [==============================] - 0s 26ms/step - loss: 8556.0596
Epoch 6/400
1/1 [==============================] - 0s 26ms/step - loss: 8264.1025
Epoch 7/400
1/1 [==============================] - 0s 20ms/step - loss: 7924.2231
Epoch 8/400
1/1 [==============================] - 0s 21ms/step - loss: 

In [5]:
"""
Multi-Step LSTM Models
A time series forecasting problem that requires a prediction of multiple time steps into the future can be referred to as multi-step time series forecasting.
There are two main types of LSTM models that can be used for multi-step forecasting; they are:

Vector Output Model
Encoder-Decoder Model

As with one-step forecasting, a time series used for multi-step time series forecasting must be split into samples with input and output components.
"""
"""
The split_sequence() function below implements this behavior and will split a given univariate time series into samples with a specified number of input and output time steps.
"""
# Multi-step data preparation
import numpy as np

# Split a univariate sequence into input/output samples
def split_sequence(sequence, n_steps_in, n_steps_out):
    X, y = [], []
    for i in range(len(sequence)):
        # Find the end of the input sequence
        end_ix = i + n_steps_in
        # Find the end of the output sequence
        out_end_ix = end_ix + n_steps_out
        # Check if we are beyond the sequence
        if out_end_ix > len(sequence):
            break
        # Gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:out_end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

# Define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# Choose a number of time steps for input and output
n_steps_in, n_steps_out = 3, 2
# Split into input/output samples
X, y = split_sequence(raw_seq, n_steps_in, n_steps_out)

# Summarize the data
for i in range(len(X)):
    print(f"Input: {X[i]}, Output: {y[i]}")


Input: [10 20 30], Output: [40 50]
Input: [20 30 40], Output: [50 60]
Input: [30 40 50], Output: [60 70]
Input: [40 50 60], Output: [70 80]
Input: [50 60 70], Output: [80 90]


In [3]:
# Multi-step data preparation and Vector Model
import numpy as np
# univariate multi-step vector-output stacked lstm example
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

# Split a univariate sequence into input/output samples
def split_sequence(sequence, n_steps_in, n_steps_out):
    X, y = [], []
    for i in range(len(sequence)):
        # Find the end of the input sequence
        end_ix = i + n_steps_in
        # Find the end of the output sequence
        out_end_ix = end_ix + n_steps_out
        # Check if we are beyond the sequence
        if out_end_ix > len(sequence):
            break
        # Gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:out_end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

# Define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# Choose a number of time steps for input and output
n_steps_in, n_steps_out = 3, 2
# Split into input/output samples
X, y = split_sequence(raw_seq, n_steps_in, n_steps_out)

# Summarize the data
for i in range(len(X)):
    print(f"Input: {X[i]}, Output: {y[i]}")

# Reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

# Define model
model = Sequential()
model.add(LSTM(100, activation='relu', return_sequences=True, input_shape=(n_steps_in, n_features)))
model.add(LSTM(100, activation='relu'))
model.add(Dense(n_steps_out))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=50, verbose=0)

# Demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps_in, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

Input: [10 20 30], Output: [40 50]
Input: [20 30 40], Output: [50 60]
Input: [30 40 50], Output: [60 70]
Input: [40 50 60], Output: [70 80]
Input: [50 60 70], Output: [80 90]
[[122.8246  134.55011]]


In [4]:
"""
A model specifically developed for forecasting variable length output sequences is called the Encoder-Decoder LSTM.

The model was designed for prediction problems where there are both input and output sequences, so-called sequence-to-sequence, or seq2seq problems, such as translating text from one language to another.

This model can be used for multi-step time series forecasting.

As its name suggests, the model is comprised of two sub-models: the encoder and the decoder.

The encoder is a model responsible for reading and interpreting the input sequence. The output of the encoder is a fixed length vector that represents the model’s interpretation of the sequence. The encoder is traditionally a Vanilla LSTM model, although other encoder models can be used such as Stacked, Bidirectional, and CNN models.


"""

import numpy as np# univariate multi-step encoder-decoder lstm example
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import RepeatVector
from keras.layers import TimeDistributed

# Split a univariate sequence into input/output samples
def split_sequence(sequence, n_steps_in, n_steps_out):
    X, y = [], []
    for i in range(len(sequence)):
        # Find the end of the input sequence
        end_ix = i + n_steps_in
        # Find the end of the output sequence
        out_end_ix = end_ix + n_steps_out
        # Check if we are beyond the sequence
        if out_end_ix > len(sequence):
            break
        # Gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:out_end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

# Define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# Choose a number of time steps for input and output
n_steps_in, n_steps_out = 3, 2
# Split into input/output samples
X, y = split_sequence(raw_seq, n_steps_in, n_steps_out)

# Summarize the data
for i in range(len(X)):
    print(f"Input: {X[i]}, Output: {y[i]}")

# Reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
y = y.reshape((y.shape[0], y.shape[1], n_features))

# Define model
model = Sequential()
model.add(LSTM(100, activation='relu', input_shape=(n_steps_in, n_features)))
model.add(RepeatVector(n_steps_out))
model.add(LSTM(100, activation='relu', return_sequences=True))
model.add(TimeDistributed(Dense(1)))
model.compile(optimizer='adam', loss='mse')

# Fit model
model.fit(X, y, epochs=100, verbose=0)

# Demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps_in, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

Input: [10 20 30], Output: [40 50]
Input: [20 30 40], Output: [50 60]
Input: [30 40 50], Output: [60 70]
Input: [40 50 60], Output: [70 80]
Input: [50 60 70], Output: [80 90]
[[[100.05647 ]
  [115.419685]]]
